language: node_js

node_js:
  - "10"

cache:
  directories:
    - "node_modules"

install:
  - yarn install

script:
  - yarn run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build
  target-branch: gh-pages
  on:
    branch: master